### ISSUE TITLE
Documentation problem

### ISSUE THREAD

**Issue by agence-appy** [finller/laravel-money#24]
Hello,

I ran into a Illuminate\Database\Eloquent\InvalidCastException: Call to undefined cast [Elegantly\MoneyCast] exception while trying to use your package.

In fact it is just a documentation problem. 

In your examples you have written : 

`use Elegantly\MoneyCast;
`

The correct use is : 

`use Elegantly\Money\MoneyCast;
`

You should update your readme file.

Thanks !

**Comment by QuentinGab** [comment]
Thx!
